# Netlify 배포 설정 파일

[build]
  # 배포 시 실행할 명령어
  command = "npm install"
  # 배포할 정적 파일 (CSS, JS, 이미지)이 있는 디렉토리
  publish = "public"
  # 서버리스 함수가 위치한 디렉토리
  functions = "functions"

[functions]
  # 모든 함수에 data 디렉토리의 파일을 포함시킵니다.
  # 중요: 이 방식은 데이터베이스 파일을 포함시키지만, 
  # Netlify 환경에서는 파일에 대한 쓰기 작업이 영구적으로 저장되지 않습니다.
  included_files = ["data/**"]

[[redirects]]
  # 모든 요청을 서버리스 함수로 전달합니다.
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
