[build]
  command = "echo 'No build command needed'"
  publish = "public"
  functions = "functions"

[functions]
  included_files = ["views/**", "data/**"]

[dev]
  command = "node functions/server.js"
  targetPort = 8080
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200